services:
  python:
    container_name: can-i-binge-yet-python
    build:
      dockerfile: ./docker/python/Dockerfile
      context: ./
    entrypoint:
      - poetry
      - run
      - gunicorn
      - '-w'
      - '2'
      - '-b'
      - '0.0.0.0:8000'
      - '--reload'
      - 'wsgi:application'
    depends_on:
      - redis
    ports:
      - 8000:8000
    volumes:
      - .:/var/ciby
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-store:/data
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  node:
    container_name: can-i-binge-yet-node
    build:
      dockerfile: ./docker/node/Dockerfile
      context: ./
    volumes:
      - .:/var/ciby
    tty: true

volumes:
  redis-store:
