services:
  go:
    container_name: ciby-go
    build:
      context: ./
      dockerfile: ./docker/go/Dockerfile
    depends_on:
      - redis
    ports:
      - 8000:8000
    volumes:
      - .:/var/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      APP_ENV: 'dev'

  redis:
    container_name: ciby-redis
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-store:/data
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  node:
    container_name: ciby-node
    build:
      dockerfile: ./docker/node/Dockerfile
      context: ./
    volumes:
      - .:/var/app
    tty: true

volumes:
  redis-store:
