// Code generated by mockery v2.28.0. DO NOT EDIT.

package file

import mock "github.com/stretchr/testify/mock"

// MockFileReaderInterface is an autogenerated mock type for the FileReaderInterface type
type MockFileReaderInterface struct {
	mock.Mock
}

type MockFileReaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileReaderInterface) EXPECT() *MockFileReaderInterface_Expecter {
	return &MockFileReaderInterface_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: filename
func (_m *MockFileReaderInterface) Read(filename string) (string, error) {
	ret := _m.Called(filename)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(filename)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileReaderInterface_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockFileReaderInterface_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - filename string
func (_e *MockFileReaderInterface_Expecter) Read(filename interface{}) *MockFileReaderInterface_Read_Call {
	return &MockFileReaderInterface_Read_Call{Call: _e.mock.On("Read", filename)}
}

func (_c *MockFileReaderInterface_Read_Call) Run(run func(filename string)) *MockFileReaderInterface_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileReaderInterface_Read_Call) Return(_a0 string, _a1 error) *MockFileReaderInterface_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileReaderInterface_Read_Call) RunAndReturn(run func(string) (string, error)) *MockFileReaderInterface_Read_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockFileReaderInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFileReaderInterface creates a new instance of MockFileReaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFileReaderInterface(t mockConstructorTestingTNewMockFileReaderInterface) *MockFileReaderInterface {
	mock := &MockFileReaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
