name: Test and Deploy

on: [push]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test_go:
    name: Go tests (Go ${{ matrix.go-versions }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-versions: [1.21.0]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-versions }}

      - name: Build
        run: go build -v ./src/go

      - name: Run unit tests
        run: go test -v ./src/go/...

      - name: Vet Go code
        run: go vet -v ./src/go/...

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./src/go/...

  test_typescript:
    name: TypeScript tests (Node ${{ matrix.node-versions }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [19]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
          cache: 'yarn'

      - name: Install yarn packages
        run: yarn install --immutable

      - name: Run TypeScript unit tests
        run: yarn run jest

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: ['test_go', 'test_typescript']
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
          cache: 'yarn'
  
      - name: Install yarn packages
        run: yarn install --immutable
  
      - name: Build assets
        run: yarn run webpack --config webpack.production.js
  
      - uses: superfly/flyctl-actions/setup-flyctl@master
  
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only --ignorefile .dockerignore.production
